### ISSUE TITLE
Screen rotation issue.

### ISSUE THREAD

**Issue by cwpeterson** [NightscoutFoundation/xDrip#1269]
I have a Pixel 4 XL running android 10, March security patch. Since installing the Feb 20 nightly, when you rotate from portrait to landscape and back to portrait, it doesn't properly resize the screen. I updated today to the current March 11 nightly and it still has the same issue. Didn't see this until I updated to the Feb 20 build, unfortunately I don't know which build I had installed prior to Feb 20.

![Screenshot_20200311-140251](https://user-images.githubusercontent.com/12939749/76453757-68f51c80-63a1-11ea-987f-1e3d571a441c.png)

**Comment by steve8x8** [comment]
Running 8ba59ae-2020.03.11 on an OPO (Nougat 7.1.2), not seeing this happening. Is this an Android 10 thing?

**Comment by cwpeterson** [comment]
Been running Android 10 since it came out, this is the first time this has happened and started after I installed the Feb 20 nightly. That's all I know.

**Comment by JonathanM32** [comment]
I am also having this issue on a pixel 4 xl

**Comment by cwpeterson** [comment]
I just installed the latest nightly and still seeing this. Glad I'm not the only one.

**Comment by JonathanM32** [comment]
Latest nightly still affected. Any chance this will get fixed?

**Comment by JonathanM32** [comment]
The latest nightly is still affected.

**Comment by JonathanM32** [comment]
Incidentally, updating to Android 11 fixed it

**Comment by cwpeterson** [comment]
Interesting! I was holding off updating as I wasn't sure if it would be compatible.

**Comment by Navid200** [comment]
Is this still happening?

**Comment by JonathanM32** [comment]
@Navid200 not on Android 11

**Comment by Navid200** [comment]
How about @cwpeterson ?

**Comment by cwpeterson** [comment]
It was resolved in Android 11. Thanks.

**Comment by farcusnz** [comment]
This bug is still present in Android 10.
Confirmed on Pixel 3 and Mi A2 (running android one)
Can the bug be reopened?

**Comment by Navid200** [comment]
@jamorham @AdrianLxM 

Guys, 
Any hints/suggestions please?

**Comment by revronfrancey** [comment]
yes, yes, yes!  this is happening to me and i think i have reached the state of going bonkers trying to figure out why this is happening.  navid fo pointed me here.  yes, this also happened to me after taking the suggested update that i think was announced as a solid update.  so, i never considered it was because of a bug in the new update.  my previous version was frpm an october 25th or so time period from a few years back.  i have a motorola g power running android v10.

**Comment by Navid200** [comment]
There are times a version of Android causes some problems and Android updates are made to address some such issues.  
The fact that anyone who updated to Android 11 did not experience this problem any longer suggests a problem caused by Android.  

Even if you are using a phone that is not going to receive Android 11, you should still install the latest updates provided by your phone manufacturer.
If you have updated to the latest patches available for your phone and you are still experiencing this problem, please let me know and I will see if I can fix it.
