### ISSUE TITLE
Xdrip + (Delay by reading raw values) 

### ISSUE THREAD

**Issue by Artemdrip** [NightscoutFoundation/xDrip#1406]
I discovered that there is a delay by reading raw values ​​in Xdrip +.
This delay is caused by the patched Libre 2 app or sensor.
This delays are summarized and if the delay is longer than 3 minutes, Xdrip + leaves a gap on the graph.
This happens with me every 4 hours.

This delay can not be avoided, but I think it can be compensated in the Xdrip+ Code. If  Xdrip + reading only 4 raw values ​​for the next value when the delay ist more than one minute. 

You can see the discussion of this issue here  https://github.com/NightscoutFoundation/xDrip/pull/1401

![90328934-da647700-dfa0-11ea-9d75-b476bf21b6a1](https://user-images.githubusercontent.com/69725840/90342336-ba1bd300-e007-11ea-9bbc-7f91773b9dac.jpg)
![IMG_20200815_213514](https://user-images.githubusercontent.com/69725840/90342337-bbe59680-e007-11ea-9f89-81c2d3050c42.jpg)

A lot of people see this Problem (Nightly build 25th Jul 2020)

**Comment by smuething** [comment]
I've taken a look at the code and I think the problem is this:

- Internally, xDrip does not work on a fixed 5 min schedule.
- The libre receiver code runs every time the patched app sends a new raw value, and if the most recent bg reading is older than 4.5 minutes, the code calculates a new reading from the most recent raw values. It does not look at how many values there are, in fact, the current version uses all raw values from the last 20 minutes to calculate a weighted average (that's why your green readings are so much smoother than the white raw values). The new value is stored in the database with the timestamp of the most recent raw value that the app received, and those raw values only come in every 63 seconds or so.
- When creating the chart shown above, xDrip reads all calculated bg readings from the database and adds them to the chart. *But*: In order to create a nice even spacing of the points, it moves the displayed point to an exact multiple of 2.5 min (always rounding down). If you look closely at your picture, you can see that the gaps are a little smaller than a full circle: That's because the value before the gap is at 16:12:30, and the value after the gap got clamped to 16:20:00. The *actual* readings happened up to 2.5 min later.
- At the gap, the following happened: The value before the gap was actually received at 16:14:59, which got rounded down to 16:12:30, and the value after the gap was received at 16:20:02, which then got rounded down to 16:20:00.

**Comment by smuething** [comment]
I think this should be fixed at the display level, not at the data collection level:
- I would not want to store data in the database that was modified just to look it nice in the chart
- Only calculating values at 5 min increments is a bad idea as well: Maybe your phone was out of range of your sensor for 5:10 since the last bg reading. If the next bg reading was only calculated at exact 5 min increments, you would have to wait for almost 5 more minutes before getting a new value from xDrip (not just in the chart, but also in the number display).
- One option would be to add a preference that disables the clamping to 2.5 min increments, which would solve the problem, but it would still generate an irregular spacing of the points in x direction, e.g. if you missed the fifth new value, all following bg readings would shift a fifth of a point to the right.

**Comment by Navid200** [comment]
Is anyone still seeing the occasional gaps shown in the screenshot using the current stable release or any Nightly after?

**Comment by Navid200** [comment]
Closing due to inactivity.
