### ISSUE TITLE
Wear complication showing wrong BG value

### ISSUE THREAD

**Issue by gregorybel** [NightscoutFoundation/xDrip#270]
Hi

I use last code from today and when using plugin datricsae, wear complication shows "xdrip original" value instead of "datricsae" value, see pictures:

![2018-01-14 16 41 14](https://user-images.githubusercontent.com/24234385/34917843-b7363798-f94b-11e7-83e1-e258ae578080.jpg)

![2018-01-14 16 40 41](https://user-images.githubusercontent.com/24234385/34917845-b9f02e1c-f94b-11e7-94c2-dc49f3f8e72e.png)

could you please solve it?

**Comment by jamorham** [comment]
I am working on this now.

**Comment by jamorham** [comment]
This should be fixed in the 15th Jan nightly which is available now.

**Comment by Thasgolas** [comment]
Which watch faces work with that?

**Comment by gregorybel** [comment]
@jamorham sorry but it seems not to work, I still see xdrip original value.
It is even worser as now there is a new string at end of loop status (-7.55), due ro change for Pebble?

![2018-01-15 22 50 21](https://user-images.githubusercontent.com/24234385/34963074-d7355d48-fa46-11e7-9b4b-56845f606a1f.jpg)

**Comment by gregorybel** [comment]
@Thasgolas any supporting complication, look at skymaster for example.

**Comment by jamorham** [comment]
@gregorybel isn't the -7.55 shown at the end part of the received status string?

**Comment by gregorybel** [comment]
No it is not part, this has been introduced since modificatios from yesterday.

and unfortunately, bg value is still wrong.

**Comment by jamorham** [comment]
Please try the Jan 16th Nightly to resolve this issue. thanks

**Comment by jamorham** [comment]
@gregorybel any joy with this version?

**Comment by gregorybel** [comment]
@jamorham yeah it yorks fine now, thanks a lot! Sorry, yesterday did not manage to test it.
