### ISSUE TITLE
Android Wear Complication displays "Null, Null" with NSClient follower

### ISSUE THREAD

**Issue by ins5736** [NightscoutFoundation/xDrip#325]
Xdrip+ used as a Sync follower with NSClient app as local broadcaster. BG data displays on the phone app, on the Xdrip+ watchfaces, but not on the Xdrip+ Complication.

Logs sent from Xdrip+ app. I'm trying to pull logs from the watch itself, but haven't gotten adb connected from the phone as of yet.

Phone: Pixel XL, Android 8.1
Watch: Ticwatch e, AW 2.9.0.185193291

![image](https://user-images.githubusercontent.com/6577649/36846701-ad061fc0-1d29-11e8-9019-8f35c2d2af2b.png)

**Comment by jamorham** [comment]
Try the May 11th nightly. This should be fixed now

**Comment by sfe87** [comment]
Hi there, firstly thanks for all the great work.

I've got the same issue as the original post, same setup / phone / watch, and watch faces work but complications just say null. 

I've tried to nightly build as suggested, and the usual restarting of phone and watch etc is there anything else I can look at? 

Thanks in advance,
Cheers

**Comment by ins5736** [comment]
Sorry for the delayed response. I still do not get data on the xdrip+ complication using the nightly build.

**Comment by KennyZR** [comment]
Same issue here on Michael Kors Access Greyson Wear 2.0 smartwatch,

**Comment by mustacheride** [comment]
Same issue on Skagen Falster Wear 2.0 with Pixel 2 on Android 8.1

**Comment by Evanvanovermeiren** [comment]
Same issue for me as well.  Pixel 2/xdrip follower/fossil explorist

**Comment by jamorham** [comment]
If you are experiencing this issue, please let me know which xDrip+ version you are using and the collector type.

I have tested this with G5 native on 21st Aug nightly and complications are working fine here. 

If you are not using the latest nightly please update to it and also uninstall and reinstall the app from your watch (if it is running AW2.0) as on android wear 2 the app doesn't automatically update.

**Comment by Evanvanovermeiren** [comment]
watch 55dcd85
phone 55dcd85 set as xdrip follower
using nightscout
dexcom g6 - iphone6 with dexcom g6 app

**Comment by jamorham** [comment]
@Evanvanovermeiren so your phone is a follower from nightscout, are you using NSClient with it?

**Comment by sfe87** [comment]
I was on 24f1ee2-2018.07.26 both phone / watch and now 55dcd85-2018.08.21 on both, still showing null unfortunately!.

Currently iPhone SE with Dexcom G6 app (but had same issue with G5) to Nightscout (0.10.2-release-20171201). 

This is then going to a Pixel XL running Android 9 (Was 8 with same issue) with AndroidAPS 2.0-RC4 (Similarly this was NSClient but tried this as a newer version to see if helped), with finally xDrip+ running as xDrip+ Sync Follower

Thanks!

**Comment by Evanvanovermeiren** [comment]
@jamorham - yes I'm using nsclient

**Comment by Evanvanovermeiren** [comment]
@jamorham - and in using version 1.58

**Comment by ins5736** [comment]
@jamorham xdrip+ sync with nsclient 1.58

Updated to 8/21 nightly, and reinstalled watch app. Restarted both both phone and watch, but complication still reads null.

Pixel XL, ticwatch e

**Comment by jamorham** [comment]
@sfe87 so you are both using NSClient with the phone in follower mode. I expect that is the code path which isn't populating the complication correctly. I will check it out.

**Comment by sfe87** [comment]
@jamorham Yup! Cheers for looking into this its much appreciated, its not really a critical issue compared to the scope of the rest of the app so thank you!

**Comment by Evanvanovermeiren** [comment]
@jamorham - any updates?

**Comment by ins5736** [comment]
Continue updating the latest beta xdrip+ but the issue persists.
1/10/19 xdrip
1.58 nsclient

**Comment by BigWebstas** [comment]
Does anything differ from nsclient to xdripfollower? i am not using nightscout to sync just the built in xdrip follower and i am getting the Null/null issue as well

**Comment by gregorybel** [comment]
Hi all, 
I have same issue with aaps as data source, I tracked the issue and found a workaorund, see my branch rebase on current xdrip master:

https://github.com/gregorybel/xDrip/commits/gregorybel-workaround-complication-null

Maybe you want to try it and check wether it solves issue for you too. But please note this is only a dirty workaround, not a proper solution. 

Maybe this will help somebody else find the correct solution.

Gregory

**Comment by rustymonkey** [comment]
Hi I'm seeing this as well. Using Xdrip+ 2020.11.27 on a Pixel 2 XL (running Android 11) with Android Wear on a Fossil Gen 5. 
Xdrip+ is configured with: Hardware data source: Nightscout follower; 'Download treatments' enabled. A separate NS client is not installed.

Xdrip+ displays BG data correctly on the phone, and on the xDrip Watchface. However, the watch complication shows 'Null', 'Null'.

**Comment by tolot27** [comment]
@gregorybel Do you think this is a duplicate of #303? They are quite similar.

**Comment by gregorybel** [comment]
I think so, at least the root cause.

**Comment by Navid200** [comment]
Please let me know if you think this should have a dedicated open issue and why.
https://github.com/NightscoutFoundation/xDrip/issues/303
